### PR TITLE
Server store api

### PR DESCRIPTION
**Pull request by mjg17**
Time to merge the backend server store code and tests into the main redux branch?

### CODE REVIEW

**Comment by katjad** [comment]
Wow, looks great. The tests! Only thing I am wondering whether to actually commit the testbd.js file (would an empty one also work? or the one written by the tests?) so that the Travis CI build would pass

**Comment by katjad** [comment]
Although that might not even be guaranteed? I get the tests to pass locally by just creating that file :)

**Comment by mjg17** [comment]
Nope this is a code error in my tests! I just was always running with the previous version hanging around.

I'll fix and resubmit the pull request.

**Comment by mjg17** [comment]
That's fixed Travis :-)

**Comment by katjad** [comment]
Great, thanks! Merged :)

**Pull request merged**
