### PR TITLE
Global replace term "organisation" with "item"

### PR DESCRIPTION
**Pull request by STRAYKR**
Replaced all occurrences of 'organisation' with 'item'. Matched & replaced lowercase, uppercase, titlecase, and plural usage in files and filenames. Tests passed before and after.

#proudMoment
#myFirstRealLifePullRequest
#hopeItsOk?!

### CODE REVIEW

**Comment by rinse0ut** [comment]
Nice work Tim! 👍

**Comment by rinse0ut** [comment]
Please amend the README and put a note about it being formerly the Organisations Database Project.

**Comment by katjad** [comment]
:+1: yay, looks all good. I pulled, and I also merged it into my tiles branch without any big problems; all tests running fine

**Comment by rinse0ut** [comment]
README is still todo btw.

**Comment by katjad** [comment]
okay, I can do that

**Comment by rinse0ut** [comment]
Spot on Katja.  Great documentation as always.

**Pull request merged**
